source 'https://rubygems.org'

gem 'sinatra', '~> 4.0'
gem 'sqlite3'
gem 'activerecord'
gem 'sinatra-activerecord', '~> 2.0', '>= 2.0.27'
gem 'rake'
gem 'rack', '~> 3.0', '>= 3.0.9.1'
gem 'rackup', '~> 2.1'
gem 'puma', '~> 6.4', '>= 6.4.2'